In [2]:
import numpy as np

x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x1

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

In [0]:
x1 = np.array([5.1, 3.5, 1.4, 0.2])
x1

array([5.1, 3.5, 1.4, 0.2])

In [0]:
A = np.array([[11, 12, 13], [21, 22, 23]])
A

array([[11, 12, 13],
       [21, 22, 23]])

In [0]:
A.T

array([[11, 21],
       [12, 22],
       [13, 23]])

In [0]:
x1

array([5.1, 3.5, 1.4, 0.2])

In [0]:
x1.T

array([5.1, 3.5, 1.4, 0.2])

In [0]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [0]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])
x+y

array([10, 12, 14, 16, 18])

In [0]:
x-y

array([10, 10, 10, 10, 10])

In [0]:
np.array([[5, 6], [7, 8]]) + np.array([[10, 20], [30, 40]]) - np.array([[1, 2], [3, 4]])

array([[14, 24],
       [34, 44]])

In [0]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])
np.dot(x.T, y)

array([[32]])

In [5]:
x = np.arange(10)
N = len(x)
np.dot(np.ones(N), x) / N

4.5

In [0]:
x.mean()

4.5

In [0]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 8], [7, 6]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [0]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

In [0]:
np.dot(A, B+C)

array([[42, 42],
       [98, 98]])

In [0]:
np.dot(A, B) + np.dot(A, C)

array([[42, 42],
       [98, 98]])

In [0]:
np.dot(A+B, C)

array([[110,  96],
       [174, 152]])

In [0]:
np.dot(A, C) + np.dot(B, C)

array([[110,  96],
       [174, 152]])

In [0]:
(A+B).T

array([[ 6, 10],
       [ 8, 12]])

In [0]:
A.T + B.T

array([[ 6, 10],
       [ 8, 12]])

In [0]:
(np.dot(A, B)).T

array([[19, 43],
       [22, 50]])

In [0]:
np.dot(B.T, A.T)

array([[19, 43],
       [22, 50]])

In [0]:
A = np.array([[1, 2], [3, 4]])
I = np.eye(2)
np.dot(A, I)

array([[1., 2.],
       [3., 4.]])

In [0]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.]])

In [0]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [0]:
A = np.arange(1, 10).reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.dot(np.dot(x, A), x)

228

In [0]:
x = np.random.randint(low=1, high=10, size=(5, 3))
print(x)

[[1 6 3]
 [2 9 2]
 [7 6 6]
 [6 6 3]
 [3 8 9]]


In [0]:
L1_norm = np.linalg.norm(x, axis=1, ord=1)
print(L1_norm)
print("shape:", L1_norm.shape)

[10. 13. 19. 15. 20.]
shape: (5,)


In [0]:
L2_norm = np.linalg.norm(x, axis=1, ord=2)
print(L2_norm)
print("shape:", L2_norm.shape)

[ 6.78232998  9.43398113 11.          9.         12.40967365]
shape: (5,)


In [0]:
A = (np.arange(9) - 4).reshape((3, 3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [0]:
np.linalg.norm(A)

7.745966692414834

In [0]:
np.trace(np.eye(3))

3.0

In [0]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

0.0

In [0]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [0]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [0]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [0]:
x = np.dot(Ainv, b)
x

array([[1.],
       [1.],
       [1.]])

In [0]:
np.dot(A, x) - b

array([[0.],
       [0.],
       [0.]])

In [15]:
x2 = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
y = np.array([2, 2, 3, 4.1])
x, _, _, _= np.linalg.lstsq(x2, y)
x.T

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


array([1.03333333, 0.95      , 1.05      ])

In [0]:
A = np.array([[1, -2], [2, -3]])
w1, V1 = np.linalg.eig(A)
w1

array([-0.99999998, -1.00000002])

In [0]:
V1

array([[0.70710678, 0.70710678],
       [0.70710678, 0.70710678]])

In [0]:
B = np.array([[2, 3], [2, 1]])
w2, V2 = np.linalg.eig(B)
w2

array([ 4., -1.])

In [0]:
V2

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [0]:
C = np.array([[0, -1], [1, 0]])
W3, V3 = np.linalg.eig(C)
W3

array([0.+1.j, 0.-1.j])

In [0]:
V3

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

In [0]:
from numpy.linalg import svd

A = np.array([[3, -1], [1, 3], [1, 1]])
U, S, VT = svd(A)
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -2.06937879e-16,  9.12870929e-01]])

In [0]:
S

array([3.46410162, 3.16227766])

In [0]:
np.diag(S, 1)[:, 1:]

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [0]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [0]:
U.dot(np.diag(S, 1)[:, 1:]).dot(VT)

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])